const data = {
    products : [
        {
            name: "Longhorn Leather Jacket",
            var: 'longhorn-leather-jacket',
            category: 'Shirts',
            image: "https://images.footballfanatics.com/texas-longhorns/mens-columbia-gray-texas-longhorns-ascender-ii-full-zip-jacket_pi4889000_altimages_ff_4889935-bc277a44770222ef546falt2_full.jpg?_hv=2&w=900",
            size: "M",
            leaseStart: "2021-11-01",
            leaseEnd: "2021-11-30",
            lengthOfRental: 5,
            price: 999,
            description: "Vintage University of Texas Longhorn Leather Jacket. In a very good condition. Embroidered logo on the front and back",
        },
        {
            name: "Texas Exes Carhartt Detroit Jacket",
            var: 'texas-exes-carhartt-detroit-jacket',
            category: 'Jackets',
            image: "https://www.universitycoop.com/media/product-images/1005103828-Brown-20.jpg?resizeid=5&resizeh=1200&resizew=1200",
            size: "M",
            leaseStart: "2021-11-01",
            leaseEnd: "2021-11-30",
            lengthOfRental: 5,
            price: 999,
            description: "Texas Exes Detroit Jacket. New, good condition. Water-repellant and wind-resistent.",
        },
        {
            name: "University Of Texas - School Of Nursing Lab Coat",
            var: 'ut-lab-coat',
            category: 'Lab Coats',
            image: "https://www.universitycoop.com/media/product-images/1005400-default-1.jpg?resizeid=5&resizeh=1200&resizew=1200",
            size: "M",
            leaseStart: "2021-11-01",
            leaseEnd: "2021-11-30",
            lengthOfRental: 5,
            price: 999,
            description: "This University of Texas at Austin, School of Nursing Lab Coat has a soil release finish, moisture wicking technology, and is wrinkle resistant.",
        },
        {
            name: "Women's Formal Office Business Work Jacket Skirt Suit Set",
            var: 'business-work-jacket-skirt',
            category: 'Business Casual',
            image: "https://www.universitycoop.com/media/product-images/1005400-default-1.jpg?resizeid=5&resizeh=1200&resizew=1200",
            size: "M",
            leaseStart: "2021-11-01",
            leaseEnd: "2021-11-30",
            lengthOfRental: 5,
            price: 999,
            description: "Marycrafts Women's Formal Office Business Shirt Jacket Skirt Suit is made of high quality stretchy ponte de roma fabric. The fabric is incredibly soft, stretchy, comfortable and durable to hug your body.",
        },
        {
            name: "Longhorn Leather Jacket",
            var: 'longhorn-leather-jacket',
            category: 'Shirts',
            image: "https://images.footballfanatics.com/texas-longhorns/mens-columbia-gray-texas-longhorns-ascender-ii-full-zip-jacket_pi4889000_altimages_ff_4889935-bc277a44770222ef546falt2_full.jpg?_hv=2&w=900",
            size: "M",
            leaseStart: "2021-11-01",
            leaseEnd: "2021-11-30",
            lengthOfRental: 5,
            price: 999,
            description: "Vintage University of Texas Longhorn Leather Jacket. In a very good condition. Embroidered logo on the front and back",
        },
        {
            name: "Texas Exes Carhartt Detroit Jacket",
            var: 'texas-exes-carhartt-detroit-jacket',
            category: 'Jackets',
            image: "https://www.universitycoop.com/media/product-images/1005103828-Brown-20.jpg?resizeid=5&resizeh=1200&resizew=1200",
            size: "M",
            leaseStart: "2021-11-01",
            leaseEnd: "2021-11-30",
            lengthOfRental: 5,
            price: 999,
            description: "Texas Exes Detroit Jacket. New, good condition. Water-repellant and wind-resistent.",
        },
    ],
};

export default data;